In [27]:
import pandas as pd

In [28]:
!pip install -q kaggle

In [29]:
import os
from google.colab import userdata

os.environ["KAGGLE_USERNAME"] = userdata.get("Kaggle_username")
os.environ["KAGGLE_KEY"] = userdata.get("Kaggle_KEY")

In [30]:
!kaggle datasets download -d kaggle/recipe-ingredients-dataset --unzip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/kaggle/recipe-ingredients-dataset
License(s): unknown
Downloading recipe-ingredients-dataset.zip to /content
100% 2.23M/2.23M [00:00<00:00, 65.4MB/s]

In [31]:
data= pd.read_json('test.json')
data

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [32]:
# for sql go and study video no 16 of campus x left at the moment

In [33]:
# using api of a website

In [34]:
import requests

In [35]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8f874d512b9be86dfccf6cfc6171566f")

In [36]:
movie=pd.DataFrame(response.json()['results'])[['id','title','original_title','overview']]

In [37]:
movie=pd.DataFrame() # created new empty dataframe

In [38]:
for i in range(1, 429):
  response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=8f874d512b9be86dfccf6cfc6171566f&page={i}")
  if response.status_code == 200:
    movie_data = pd.DataFrame(response.json()['results'])[['id','title','original_title','overview']]
    movie = pd.concat([movie, movie_data], ignore_index=True)
  else:
    print(f"Failed to fetch page {i}")

In [39]:
movie.to_csv('movie.csv')

In [40]:
movie=pd.read_csv('movie.csv')

In [41]:
movie

,Unnamed: 0,id,title,original_title,overview
0,0,1632181,Accidental Partners,Socias por accidente,Two women discover they were both scammed by t...
1,1,1007757,Swapped,Swapped,"A small woodland creature and a majestic bird,..."
2,2,278,The Shawshank Redemption,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
3,3,936075,Michael,Michael,"The story of Michael Jackson, one of the most ..."
4,4,238,The Godfather,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
...,...,...,...,...,...
8555,8555,1901,In Good Company,In Good Company,Dan Foreman is a seasoned advertisement sales ...
8556,8556,605804,The Wretched,The Wretched,"A rebellious teenage boy, struggling with his ..."
8557,8557,74944,War of the Buttons,La Guerre des boutons,"A village in the South of France, 1960. A band..."
8558,8558,13683,Tarzan & Jane,Tarzan & Jane,With the first anniversary of her wedding to T...
8559,8559,6623,The Peacemaker,The Peacemaker,When a train carrying atomic warheads mysterio...

In [42]:
# in this way we can create a dataset form the api of a website to directly to the csv formate