In [23]:
import numpy as np
import pandas as pd

In [24]:
!pip install -q kaggle

In [25]:
import os
from google.colab import userdata

os.environ["KAGGLE_USERNAME"] = userdata.get("Kaggle_username")
os.environ["KAGGLE_KEY"] = userdata.get("Kaggle_KEY")

In [26]:
!kaggle datasets download -d osama12bin/cars-csv --unzip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/osama12bin/cars-csv
License(s): unknown
Downloading cars-csv.zip to /content
100% 65.1k/65.1k [00:00<00:00, 44.3MB/s]

In [27]:
df=pd.read_csv("cars.csv")

In [28]:
df.sample(5)

         brand  km_driven    fuel         owner  selling_price
6842  Mahindra     110000  Diesel   First Owner         650000
3776      Ford      14200  Petrol   First Owner         550000
6656   Hyundai      56000  Petrol   Third Owner         500000
7451      Ford      84000  Diesel  Second Owner         210000
6380    Maruti      50000  Petrol   First Owner         400000

In [29]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [30]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [31]:

pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [33]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
ohe = OneHotEncoder()

In [36]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [37]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [38]:
X_train_new.shape

(6502, 9)

In [40]:
# Convert the sparse matrix X_train_new to a dense array to match dimensions
np.hstack((X_train[['brand','km_driven']].values, X_train_new.toarray()))

array([['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 0.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [41]:
counts = df['brand'].value_counts()

In [42]:
df['brand'].nunique()
threshold = 100

In [43]:
repl = counts[counts <= threshold].index

In [44]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
5840,False,False,False,False,False,False,True,False,False,False,False,False,False
5195,False,False,False,False,False,False,False,False,False,True,False,False,False
2259,False,False,False,False,True,False,False,False,False,False,False,False,False
1515,False,False,False,False,False,True,False,False,False,False,False,False,False
4160,False,False,False,False,False,False,True,False,False,False,False,False,False