In [18]:
import numpy as np
import pandas as pd

In [19]:
!pip install -q kaggle

In [20]:
import os
from google.colab import userdata

os.environ["KAGGLE_USERNAME"] = userdata.get("Kaggle_username")
os.environ["KAGGLE_KEY"] = userdata.get("Kaggle_KEY")

In [21]:
!kaggle datasets download -d aaditya1gautam/customer-csv --unzip

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/aaditya1gautam/customer-csv
License(s): MIT
Downloading customer-csv.zip to /content
100% 471/471 [00:00<00:00, 1.08MB/s]

In [22]:
df=pd.read_csv("customer.csv")

In [23]:
df.sample(5)

    age  gender review education purchased
35   74    Male   Poor    School       Yes
48   39  Female   Good        UG       Yes
6    18    Male   Good    School        No
3    72  Female   Good        PG        No
15   75    Male   Poor        UG        No

In [24]:
df = df.iloc[:, 2:]

# Display first 5 rows
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [25]:
X = df.drop('purchased', axis=1)
y = df['purchased']

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [27]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(
    categories=[
        ['Poor', 'Average', 'Good'],
        ['School', 'UG', 'PG']
    ]
)

In [28]:
oe.fit(X_train)

# Transform train and test data
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

print("Encoded X_train")
print(X_train)

print("\nCategories learned:")
print(oe.categories_)

Encoded X_train
[[0. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [2. 2.]
 [2. 0.]
 [2. 2.]
 [0. 2.]
 [2. 2.]
 [0. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 2.]
 [2. 2.]
 [1. 0.]
 [1. 1.]
 [2. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]
 [2. 0.]
 [2. 1.]
 [0. 2.]
 [2. 0.]
 [2. 1.]
 [1. 0.]
 [0. 0.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]]

Categories learned:
[array(['Poor', 'Average', 'Good'], dtype=object), array(['School', 'UG', 'PG'], dtype=object)]

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Learn mapping
le.fit(y_train)

print("\nTarget Classes:")
print(le.classes_)

Target Classes:
['No' 'Yes']

In [30]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

print("\nEncoded y_train")
print(y_train)

Encoded y_train
[0 0 1 0 0 0 1 0 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 1
 1 0 0]