In [ ]:
!pip install -q kaggle

from dotenv import load_dotenv
import os

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

print(GEMINI_API_KEY is not None)

!kaggle datasets download -d theprtsh/sih-2025-problem-dataset --unzip

False
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/theprtsh/sih-2025-problem-dataset
License(s): GPL-3.0
Downloading sih-2025-problem-dataset.zip to /content
100% 72.8k/72.8k [00:00<00:00, 419kB/s]

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("sih-2025-ps.csv")

In [ ]:
df.head()

,Category,Dataset_Links,Department,Description,Organization,Problem_Statement_ID,Problem_Statement_Title,Theme,Youtube_Links
0,Software,NaN,Ministry of Health & Family Welfare/Ministry o...,Problem Statement This problem statement propo...,Ministry of Development of North Eastern Region,25001,Smart Community Health Monitoring and Early Wa...,MedTech / BioTech / HealthTech,NaN
1,Software,NaN,Ministry of Tourism/ Ministry of Home Affairs ...,Problem Statement This problem statement propo...,Ministry of Development of North Eastern Region,25002,Smart Tourist Safety Monitoring & Incident Res...,Travel & Tourism,NaN
2,Hardware,NaN,Ministry of Rural Development/ Ministry of Env...,Problem Statement This problem statement propo...,Ministry of Development of North Eastern Region,25003,Low-Cost smart transportation solution for Agr...,Transportation & Logistics,NaN
3,Software,NaN,Department of Animal Husbandry & Dairying (DoA...,Background The Government of India is implemen...,"Ministry of Fisheries, Animal Husbandry & Dair...",25004,lmage based breed recognition for cattle and b...,"Agriculture, FoodTech & Rural Development",NaN
4,Software,NaN,Department of Animal Husbandry & Dairying (DoA...,"Background: In dairy farming, evaluating the b...","Ministry of Fisheries, Animal Husbandry & Dair...",25005,lmage based Animal Type Classification for cat...,"Agriculture, FoodTech & Rural Development",NaN

In [ ]:
df.shape

(135, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Category                 135 non-null    object
 1   Dataset_Links            5 non-null      object
 2   Department               135 non-null    object
 3   Description              135 non-null    object
 4   Organization             135 non-null    object
 5   Problem_Statement_ID     135 non-null    int64
 6   Problem_Statement_Title  135 non-null    object
 7   Theme                    135 non-null    object
 8   Youtube_Links            5 non-null      object
dtypes: int64(1), object(8)
memory usage: 9.6+ KB

In [ ]:
#removing the row with category as "Hardware" as it is not required for our analysis
df = df[df['Category'] != 'Hardware']

In [ ]:
df.sample(5)

,Category,Dataset_Links,Department,Description,Organization,Problem_Statement_ID,Problem_Statement_Title,Theme,Youtube_Links
87,Software,NaN,Higher Education Department,Background: Despite increasing digitization in...,Government of Jammu and Kashmir,25093,Centralised Digital Platform for Comprehensive...,Smart Education,https://youtu.be/-MhXozNPOeg?si=GYJ28nWtzOHYf-x8
27,Software,NaN,Department of Higher and Technical Education,Background Higher Education institutions often...,Government of Jharkhand,25028,Smart Classroom & Timetable Scheduler,Smart Education,NaN
97,Software,NaN,Directorate of Technical Education (DTE),"Background: Admissions, fee collection, hostel...",Government of Rajasthan,25103,ERP-based Integrated Student Management system,Smart Automation,NaN
119,Software,NaN,"AICTE, MIC-Student Innovation",Provide ideas in a decentralized and distribut...,AICTE,25127,Student Innovation,Blockchain & Cybersecurity,NaN
75,Software,NaN,Department of Agriculture,Problem Farmers often face critical questions ...,Government of Kerala,25076,AI-Based Farmer Query Support and Advisory System,"Agriculture, FoodTech & Rural Development",NaN

In [ ]:
df.shape

(90, 9)

In [ ]:
df[df['Theme'].isin([
    'Heritage & Culture',
    'Blockchain & Cybersecurity'
])]

,Category,Dataset_Links,Department,Description,Organization,Problem_Statement_ID,Problem_Statement_Title,Theme,Youtube_Links
26,Software,NaN,All India Institute of Ayurveda (AIIA),Background The Ayurvedic herbal supply chain i...,Ministry of Ayush,25027,Develop a blockchain-based system for botanica...,Blockchain & Cybersecurity,NaN
51,Software,NaN,Electronics & IT Department,Description Create an augmented reality (AR) p...,Government of Odisha,25052,AR-Based Cultural Heritage Preservation Platform,Heritage & Culture,NaN
99,Software,NaN,Indian Knowledge Systems (IKS),"Kolams (known by other narnes as muggu, rangol...",AICTE,25107,"Develop computer programs (in any language, pr...",Heritage & Culture,NaN
119,Software,NaN,"AICTE, MIC-Student Innovation",Provide ideas in a decentralized and distribut...,AICTE,25127,Student Innovation,Blockchain & Cybersecurity,NaN
122,Software,NaN,"AICTE, MIC-Student Innovation",Ideas that showcase the rich cultural heritage...,AICTE,25130,Student Innovation,Heritage & Culture,NaN

In [ ]:
df = df[~df['Theme'].isin([
    'Blockchain & Cybersecurity',
    'Heritage & Culture'
])]

In [ ]:
df.shape

(85, 9)

In [ ]:
df.to_csv('/content/final_dataframe.csv', index=False)